version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgresIdentity
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5410:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/14/data
    restart: unless-stopped