version: '3'

services:
  postgres:
    image: postgres:14
    container_name: pg_container
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/14/data
    restart: unless-stopped
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"  

  identity:
    build:
      context: ../
      dockerfile: Lappka.Identity.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "5001:80"
    depends_on:
      - postgres
    
      
    